/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.internal.bind.util.ISO8601Utils;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Scanner;

public class App {
//    public App() throws IOException {
//    }
    public static int lastQuote;
    public static int randomIndex;

    public static String getRandomQuote() throws FileNotFoundException {
        Gson gson = new Gson();
        Quote[] allQuotes = gson.fromJson(new FileReader("src/main/resources/recentquotes.json"), Quote[].class);

        //avoid using the same quote twice in a row
        while (randomIndex == lastQuote) {
            randomIndex = (int) Math.ceil(Math.random() * allQuotes.length);
        }
        lastQuote = randomIndex;

        return allQuotes[randomIndex].text + "\n-" + allQuotes[randomIndex].author;
    }

    public static String getQuoteFromAuthor(String author) throws FileNotFoundException {
        Gson gson = new Gson();
        Quote[] allQuotes = gson.fromJson(new FileReader("src/main/resources/recentquotes.json"), Quote[].class);

        int quoteCount = 1;
        Quote[] quotesFromThatAuthor = new Quote[quoteCount];
        Quote[] oldQuotes;
        for (Quote quote : allQuotes) {
            if (quote.author.contains(author)) {
                quoteCount++;
                oldQuotes = quotesFromThatAuthor;
                quotesFromThatAuthor = new Quote[quoteCount];
                for (int i = 0; i < oldQuotes.length; i++) {
                    quotesFromThatAuthor[i] = oldQuotes[i];
                }
                quotesFromThatAuthor[quoteCount - 1] = quote;
            }
        }
        randomIndex = (int) (Math.random() * quotesFromThatAuthor.length);
        return quotesFromThatAuthor[randomIndex].text + "\n-" + quotesFromThatAuthor[randomIndex].author;
    }


    public static void main(String[] args) throws FileNotFoundException {
        if (args.length == 0) {
            System.out.println(getRandomQuote());
        } else {
            System.out.println(getQuoteFromAuthor(args[0]));
        }
    }
}
